version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/libp2p/go-libp2p-core
    versions:
    - 0.8.0
    - 0.8.4
  - dependency-name: github.com/ipfs/go-ipfs-cmds
    versions:
    - 0.5.0
